UCLALibrary/californica

config/deploy.rb

Capistrano passenger restart isn't working consistently,
so restart apache2 after a successful deploy, to ensure
changes are picked up.

Restart apache after a cap deploy

---

config/fedora.yml

Since we're using the ansible roles to provision our VM dev box, we have tomcat running at 8080 already (like we would in production). This change would also mirror the Solr config, which uses the same port for production and development, 8983. I'm going to ask for reviews from all the UCLA devs though to make sure this change doesn't break any of their stuff. We could also just set the FCREPO_DEVELOPMENT_PORT environmental variable on the VM if this proposal throws a wrench in someone else's dev environment.

Change fedora dev port config to 8080

---

config/environments/production.rb
config/initializers/hyrax.rb

I followed the troubleshooting guide at
https://samvera.github.io/troubleshooting_riiif.html
Fix upload, cache, and working path:
These should be configurable with
environment variables and should
default to a directory outside of
a specific deploy.
Serve static files
Fixes #16

Fix Universal Viewer and IIIF

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

Use `DatabaseCleaner` and `ActiveFedora::Cleaner` to manage RDBMS, Fedora, and Solr state in the test suite.

Cleanup after specs

---

README.md

pull request #37 replaced the occurences of Tenejo with Californica,
however I got the Markdown syntax wrong (I blame the
tpope/vim-markdown-plugin for hiding the syntax from me), this commit
fixes that typo
fixes #42

fix markdown syntax for project name

---

config/initializers/hyrax.rb

Set the default derivative location to
/opt/derivatives so that thumbnails
don't disappear every time we make
a new release.
Fixes #51 
Fixes #54

Ensure derivatives persist between deploys

---

config/fedora.yml
config/solr.yml

Adding FEDORA_DEVELOPMENT_URL and SOLR_DEVELOPMENT_URL ENV variables.
Changing the default Fedora port back to the 8984 that DCE prefers (the VM will use the ENV vars).

Parameterize fedora and solr dev configs

---

.env.sample
.travis.yml
Gemfile
Gemfile.lock
README.md
config/cable.yml
config/database.yml
config/deploy.rb
config/fedora.yml
config/redis.yml
db/schema.rb
db/seeds.rb

- Adds `dotenv` configuration variables for more control in deployment.
- Changes capistrano config not to use nokogiri system libraries.
- Sets passenger registry directory to `/var/run`
- Changes the name of the apache service to `httpd` for Red Hat
- Switches the database over to `mysql` with `mysql2`
- Adds `pkg-config` gem

Prepare configuration for UCLA deployment

---

.rubocop.yml
app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb
spec/tasks/ingest_spec.rb

Sets works imported via the CSV parser to PUBLIC/"open" by default.
Adds an integration test checking that the CSV importer rake task is working as
expected. We setup the task and use `example.csv` to ensure it runs on a healthy
example and maps the title as expected.
Connected to #78.

Finish basic setup for CSV importer

---

config/deploy.rb

The purpose of this branch is to introduce configuration in the `deploy.rb` file to allow deployment of code via the UCLA bastion host (`jump.library.ucla.edu`). 
This allows us to maintain secure server environments - keeping firewall access in place to limit direct access to our servers. 
This configuration creates a new environment variable `VIA_JUMP` that allows the entity deploying the code to set whether or not code is deployed through the jump server or directly to the server environment. 
Supersedes #113

Enable deployment via the UCLA Jump Server

---

app/models/work.rb
spec/models/work_spec.rb

Implement a Genre term using the Europeana Data Model (EDM).
Using the RDF::Vocab::EDM module (from the `rdf-vocab` gem) makes the URI-ref easier to maintain.
Closes #64.
Replaces #112

Add `Work#genre` attribute implementation

---

app/assets/stylesheets/hyrax.scss
app/helpers/hyrax_helper.rb
app/views/_logo.html.erb
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
config/application.rb
config/environments/production.rb
config/locales/californica.en.yml
package.json

Changing all references to tenejo to californica, should address the
lingering referneces to Tenejo in the web UI. Connected to #99.

Change all references to tenejo to californica.

---

app/views/shared/_footer.html.erb
config/locales/californica.en.yml

create californica.footer.copyright_html translation for future use,
leave it blank for now
connects to #126

Remove copyright statement from footer

---

app/controllers/catalog_controller.rb
app/models/schemas/generated_resource_schema_strategy.rb
app/models/schemas/work_metadata.rb
app/models/work.rb
config/locales/blacklight.en.yml
config/locales/simple_form.en.yml
spec/models/work_spec.rb

This commit adds the repository field to the work
with the `modsrdf:locationCopySubLocation` predicate.
This commit introduces the `WorkMetadata` schema class
which is part of a pattern used in Mahonia:
https://github.com/curationexperts/mahonia
Connected to #100

Add repository field to Work

---

config/schedule.rb
lib/tasks/ingest.rake

Connected to #133 
I realize there are improvements we want to make here, like this CSV file should be an environment variable. However, I'd really like to get this in asap so the branch doesn't get stale and we can start testing a complete re-index against the latest indexing code. Right now a complete re-index is failing on the DCE RHEL box b/c fedora is falling over. I'd like to get that solved asap.

Automate daily re-indexing of news negatives

---

app/models/work.rb
config/locales/simple_form.en.yml
spec/models/work_spec.rb

This commit adds the `local_identifier` term
to the model and sets the correct label in the
simple_form locale.
Connected to #154

Add local_identifier term

---

app/models/work.rb
spec/models/work_spec.rb

This adds the latitude and longitude attributes
to the model.
This does not include searching and faceting. Because
these are one word terms, they do not need specific entries
in the the locale files.
Connected to #150
Connected to #148

Add latitude and longitude to data model

---

app/models/work.rb
config/locales/simple_form.en.yml
spec/models/work_spec.rb

This adds the funding_note term to the model.
The predicate URI is not in RDF::Vocab so it is used
directly in this commit.
Connected to #171

Add funding_note to the model

---

app/controllers/catalog_controller.rb
app/models/work.rb
config/locales/blacklight.en.yml
config/locales/simple_form.en.yml
spec/models/work_spec.rb

This commit adds the named_subject term
to the model and sets the correct label in the
simple_form locale.
It also sets up the faceting and searching
of the term as specified in the issue via the
catalog_controller.
Connected to #139

Add named_subject to model

---

app/controllers/catalog_controller.rb
app/models/work.rb
config/locales/blacklight.en.yml
config/locales/simple_form.en.yml
spec/models/work_spec.rb

to the model and sets the correct label in the
simple_form locale.
It also sets up the faceting and searching
of the term as specified in the issue via the
catalog_controller.
Connected to #142

This commit adds the rights_country term

---

app/controllers/catalog_controller.rb
app/models/work.rb
spec/models/work_spec.rb

This commit adds the dimensions term to the model
and allows the dimensions term to be facetable. Because
this is a one word term, there isn't an entry
in the locales.
Connected to #168

Add dimensions term to the model

---

spec/models/work_spec.rb

This commit adds a test for the `publisher` term.
This is present in `Hyrax::BasicMetadata` already. This
test will fail if the predicate changes upstream.
Connected to #106

Add spec for publisher

---

config/deploy/embark.rb

Copy the sandbox.rb capistrano deployment config and modify it to work
with the Vagrant-Embark VM.
Revise the copied sandbox deploy config to point at the Embark IP
Use the IP address 192.168.33.33 instead of the embark.vagrant.test
domain, because not everyone will have a domain plugin enabled for
Vagrant.
Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/89

Add a deploy configuration for the Vagrant-Embark VM

---

app/importers/californica_importer.rb
lib/tasks/ingest.rake
spec/importers/californica_importer_spec.rb

* The log file is time stamped
* It records how long the ingest process took
* The rake task uses the new importer
* Keep logic out of the rake task and in a class where it can be tested
Connected to #200

Log ingest output to a file

---

README.md

I am updating the README file to include instructions for how to execute a code deployment that tunnels through the UCLA Library jump server.

Instructions for code deployment via the UCLA Library jump server

---

.rubocop.yml
spec/features/edit_work_spec.rb
spec/rails_helper.rb

I added database cleaning to the filter hook for :clean because if you
clean fedora without also cleaning database, you might get errors about
missing Hyrax::PermissionTemplate records.

A feature spec for editing a work.  Part of story #207

---

app/importers/actor_record_importer.rb
spec/importers/actor_record_importer_spec.rb

The Hyrax ActorStack manages pre- and post-ingsest processing for new
items. This includes setting system managed dates, attaching files, initializing
workflow, etc...
This plugs our bulk ingest process into the californica-wide default stack to
ensure full processing happens for new items.
Closes #161.

Use the ActorStack when importing records

---

spec/features/create_work_spec.rb
spec/features/edit_work_spec.rb
spec/importers/actor_record_importer_spec.rb
spec/importers/californica_csv_parser_spec.rb
spec/importers/californica_importer_spec.rb
spec/rails_helper.rb
spec/support/shared_contexts/workflow.rb
spec/tasks/ingest_spec.rb

This addresses latent order dependency in the test suite. Cleanup is more systematically handled by mixing the `:truncation` and `:transaction` cleanup strategies.

Refine database cleanup strategy

---

app/importers/californica_importer.rb
spec/importers/californica_importer_spec.rb

This replaces the default `Darlingtonia::RecordImporter`, with the new `ActorRecordImporter` to route imports through the Actor Stack. We leave the dependency hard coded for now.

Use the `ActorRecordImporter` when importing via the rake task

---

app/services/reindex_service.rb
spec/services/reindex_service_spec.rb

This commit includes a service that reindexes
the contents of the repository to another solr
server.
It is intended to be used with a Rake task.
Connected to #214

Add a service to reindex to another server

---

lib/tasks/ursus.rake

You need to set an environment variable for the Ursus solr URL.  You can
run rake task like this:
URSUS_SOLR_URL="http://127.0.0.1:8987/solr/development-ursus" rake
californica:reindex_ursus
This is part of a research spike to determine how we'll set up solr for
Ursus, and how to keep Ursus up-to-date with the latest data from
Californica.

Rake task to bulk reindex the solr index for Ursus.  Part of story #214.

---

lib/tasks/ingest.rake

When destroying an `AdminSet`, the attached `PermissionTemplate` in the
relational database need to be cleaned up. If this is neglected, recreating the
default `AdminSet` (or any other admin set with a previously existing id).
The `californica:ingest:clean` task is changed to destroy existing permission
templates after running `ActiveFedora::Cleaner.clean!`.
This should restore the functionality of nightly ingest.
Closes https://github.com/UCLALibrary/amalgamated-samvera/issues/101

Clean `PermissionTemplate` instances when clean task destroys AdminSets

---

Gemfile
Gemfile.lock

We'd like to see failures on the sidekiq dashboard. This adds a tab with a list of failures (by default limited to 1000, but that's configurable), but strangely doesn't link the failures count (like retries et al. are linked). Still, good enough for a first pass.
Connected to #241

Add sidekiq-failures gem

---

app/importers/californica_csv_parser.rb
spec/importers/californica_csv_parser_spec.rb

The validator classes should use the parent parser's error stream.

Fixed a problem where error messages from validators weren't getting printed to the error log file.

---

config/schedule.rb

The nightly re-ingest isn't working and it
doesn't seem worthwhile to spend more
time on it right now. Instead, let's do
a re-ingest manually when it's warranted.
Connected to #238

Remove nightly reingest

---

app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb

This fixes a bug where the ingest fails when
masterImageName is empty.
Connected to #255

Do not fail if masterImageName is empty

---

app/controllers/catalog_controller.rb
app/models/work.rb

Previously, location was not being indexed or
displayed as a facet, so when it appeared in the
facet menu the values didn't make a lot of sense.
This change makes the location facet more useful.

Fix location facet

---

app/controllers/catalog_controller.rb

Since this value will always be the same for all
LADNN records, and it's a meaningless string
("californica_import_user@example.com") do not take
up the user's attention by displaying it.

Remove depositor field from search results

---

app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb

Some subjects have MaRC codes (e.g., $z) as
separators, instead of the usual double dash.
Normalize these so they match the standard
practice.
Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/51

Replace MaRC codes with double dashes

---

README.md

This adds instructions for how to handle a CSV export being manually edited.
Connected to  UCLALibrary/amalgamated-samvera#135

Update README with UTF-8 information

---

app/importers/californica_csv_parser.rb
spec/importers/californica_csv_parser_spec.rb

When a long running ingest fails partway through,
we want to be able to restart it where it left off.
We can now do this by setting a SKIP environment
variable like this:
SKIP=5 rake californica:ingest:sample
Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/137

Skip records with ENV['SKIP']

---

.rubocop.yml
app/importers/californica_csv_parser.rb
app/importers/californica_mapper.rb
app/importers/rights_statement_validator.rb
spec/fixtures/example-invalid-rights_statement.csv
spec/importers/californica_csv_parser_spec.rb
spec/importers/californica_mapper_spec.rb
spec/importers/rights_statement_validator_spec.rb

* The mapper will use the label from the CSV file to find the ID that needs to be stored for the rights_statement.
* A validator checks to make sure the values in the CSV file are valid.  The CSV file will be rejected if there are invalid values.
* I added the lonely operator to the 'subject' method in the mapper because it was causing errors when I tried to import CSV files that don't have a subject column.
Connected to #97

Import copyright status from CSV file. Story #97

---

.travis.yml
config/fcrepo_wrapper_test.yml
config/solr_wrapper_test.yml
lib/tasks/ci.rake

The recent travis timeouts that I've seen have had to do with downloading the solr files.  I added a cache to the travis config to keep previous downloads to avoid constantly having to re-download the same files.
This will alleviate some of the network timeout problems, but it won't fully solve them.  Even after caching the files, I still see some timeout errors from solr_wrapper's `fetch_latest_version` method.  If we decide we want to eliminate that error, we'll need to explicitly set the solr version in `config/solr_wrapper_test.yml` (and probably need to similarly set the fedora version in `config/fcrepo_wrapper_test.yml`).  If we decide to do that in the future, we can submit that as a separate PR.

Alleviate travis timeout errors by caching download zips

---

app/indexers/work_indexer.rb
spec/indexers/work_indexer_spec.rb

We want to display latitude and longitude as a single field, so I added
a solr index with the data in the format that we want to display in
Ursus.
Connected to https://github.com/UCLALibrary/ursus/issues/22

Index latitude and longitude into a single field for display. Story ursus#22

---

app/controllers/catalog_controller.rb
spec/features/import_and_show_work_spec.rb

Connected to #264
- revise search result field order in catalog_controller
- revise import and show work feature spec to verify the expected fields
appear in a search results page

Revise search result field order in catalog_controller.rb

---

app/renderers/hyrax/renderers/rights_statement_attribute_renderer.rb
config/authorities/rights_statements.yml
spec/features/edit_work_spec.rb
spec/features/import_and_show_work_spec.rb
spec/importers/californica_mapper_spec.rb

UCLA has not yet adopted rightsstatements.org so their values
are not allowed in UCLA data at this time. Instead:
* Use a placeholder URI for a UCLA specific copyright value
* Do not link copyright value to anything in the UI
* Update tests to reflect these expectations
Connected to https://github.com/UCLALibrary/californica/issues/284

Do not use rightsstatement.org values for UCLA

---

lib/tasks/ingest.rake

This will let us set this to run when we leave for the day
and hopefully, now that the timeout issue is fixed,
come back the next morning to fresh clean data.
Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/166

Add a task to clean and re-ingest in one command

---

config/routes.rb

* Changes the root route to just display search results instead of
default hyrax home page.
* Connected to #297

Front page goes to default search. Story #297

---

README.md

Add coverall badge so we can so how much of our code our tests are covering at a glance.
Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/180
[![Coverage Status](https://coveralls.io/repos/github/UCLALibrary/californica/badge.svg?branch=master)](https://coveralls.io/github/UCLALibrary/californica?branch=master)

Add coverall badge

---

.env.sample
config/initializers/hyrax.rb

Gives the option to use an external IIIF server if the IIIF_SERVER_URL env variable has been set. If it's not been set, Hyrax falls back to using the local riiif server.
Connected to [uclalibrary/amalgamated_samvera#164](https://github.com/UCLALibrary/amalgamated-samvera/issues/164)

Configure Hyrax for external IIIF server

---

.rubocop.yml
app/indexers/work_indexer.rb
app/indexers/year_parser.rb
spec/indexers/work_indexer_spec.rb
spec/indexers/year_parser_spec.rb

* Added an entry to the solr index for the integer years that correspond to the normalized_date field.
* This solr field will be used by Ursus to implement a date slider facet.
* Added a YearParser class that knows how to turn the normalized_date field into a list of integer years. 
Connected to UCLALibrary/ursus#69

 Index the years from the normalized_date field. Story UCLALibrary/ursus#69

---

spec/spec_helper.rb

This allows me to reduce visual clutter and avoid unnecessary instrumentation when I'm doing TDD.

Added an environment variable to give developer the option to disable spec profiling.

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/hyrax.scss
app/views/_masthead.html.erb
app/views/shared/_footer.html.erb

- define a new californica_yellow color in _variables.scss
- use it in the hyrax SCSS
- revise the footer and masthead templates to stop using the inverse
navbar styles
Connected to #325.search-field-header

Change header and footer colors to match the Californica Poppy

---

lib/tasks/fix_license.rake

Note that this is a temporary measure and this rake task
should not stick around past early 2019.
Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/216

Rake task to fix license

---

.travis.yml

This allows us to perform continuous deployment to the staging server for **any** tagged release - this includes our proposals of:
- `sprintX.Y`
- `X.Y.ZrcN`
- `X.Y.Z`
When a tag is created for any of the above, the release will be deployed to the stage environment.

Test if TRAVIS_TAG is not empty for stage deploy

---

Gemfile.lock

This addresses a bug where the most recent versions of
solr won't download in dev and test environments.

Upgrade solr_wrapper

---

app/importers/californica_csv_cleaner.rb
lib/tasks/ingest.rake
spec/importers/californica_csv_cleaner_spec.rb

Given a CSV with an Item Ark column, find any records
with the given arks and destroy them.
This will let us selectively re-ingest parts of the collection
as we benchmark test performance.

Use a CSV to clean records by Item Ark

---

.gitignore

FITS tends to leave a log file in the home directory that we don't need to have checked into the repo.

Remove fits.log and avoid accidentally checking it in

---

app/indexers/work_indexer.rb
spec/indexers/work_indexer_spec.rb

Connected to #358 
ARKs are available as a single-valued field for blacklight  
This requires us to add the "ark:/ " prefix to all identifiers in the  
+ local development environment
+ sample data
+ test, dev and stage and environments
+ production environments
And then re-index
---
+ modified:   app/indexers/work_indexer.rb
+ modified:   spec/indexers/work_indexer_spec.rb

Add a single value Ark to the Solr index

---

app/indexers/work_indexer.rb
spec/indexers/work_indexer_spec.rb

Add "ark:/" on the value in the solr index if it doesn't already exist
---
On branch single-value-ark_399
+ modified:   app/indexers/work_indexer.rb
+ deleted:    lib/tasks/.keep
+ modified:   spec/indexers/work_indexer_spec.rb

Make ARK available to blacklight as single-value field

---

Gemfile
Gemfile.lock

CVE-2019-8331
In Bootstrap 4 before 4.3.1 and Bootstrap 3 before 3.4.1, XSS is
possible in the tooltip or popover data-template attribute. For more
information, see:
https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

Address security issue in bootstrap-sass

---

config/deploy.rb
config/deploy/californica-dev.rb
config/deploy/californica-stage.rb
config/deploy/cd.rb
config/deploy/dce-qa.rb
config/deploy/demo.rb
config/deploy/sandbox.rb

For performance testing we need to be able to deploy to DCE
infrastructure, which is ubuntu-based. Accordingly, we need to move any
Red Hat specific capistrano commands into their specific deploy
environments, and add ubuntu-specific commands into *their* specific
deploy environments.
In other words, run `sudo systemctl restart apache2` when deploying to
ubuntu, and `sudo systemctl restart httpd` when deploying to Red Hat.

Allow deploy to ubuntu servers

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/importers/californica_csv_parser.rb
app/importers/californica_importer.rb
lib/tasks/ingest.rake
spec/features/import_and_show_work_spec.rb
spec/importers/californica_csv_parser_spec.rb
spec/importers/californica_importer_spec.rb

* Metadata-only update when the deduplication field
matches an existing record. That means it will not try to re-import
attached files, it will only update metadata and collection membership.
* Redirect logging in tests for better performance.
* Remove temporary text-only collection facet.
* Pass logging locations to DarlingtoniaImporter so success and
failure counts go to the same log location as everywhere else.
* Remove `elapsed_time` reporting from Californica in favor of the reporting now contained in Darlingtonia 
Connected to #403 
Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/275

Pared down update stack

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
app/models/ucla_metadata.rb
spec/models/collection_spec.rb
spec/models/work_spec.rb

* the local_identifier property is stored in the predicate
::RDF::Vocab::Identifiers.local
* local identifiers are not tokenized
Connected to https://github.com/UCLALibrary/californica/issues/435

Update the predicate for Local Identifier

---

docker-compose.yml

Needed for e.g. thumbnails.
connected to https://github.com/UCLALibrary/ursus/issues/239

docker: persist /opt/derivatives and /opt/uploads

---

config/schedule.rb

Don't allow files in /opt/uploads to stick around forever. Clean them up
when they've been there longer than 7 days. Generally, Californica won't
be using this directory much, but we do use it when we regenerate
derivatives, and it isn't inconceivable that someone will upload a file
via the UI.
Connected to https://github.com/UCLALibrary/californica/issues/437

Clean up /opt/uploads directory

---

app/controllers/hyrax/dashboard/collections_controller_override.rb
app/presenters/hyrax/californica_collection_presenter.rb
spec/features/show_collection_spec.rb

When UCLA metadata is added to a collection object, it should also
appear on the show view for that collection.
Connected to #431

Add metadata to collection view

---

docker/start-app.sh

Needed because the docker-compose setup keeps a local cache of gems
that occasionally needs to be updated.

docker: run bundle check || bundle install when starting web container

---

.gitignore
app/controllers/branding_info_controller.rb
config/routes.rb
spec/controllers/branding_info_controller_spec.rb

The data about where the collection banner is stored in the Californica database (not Fedora/Solr).
This adds a route and controller so that we can access
this data from ursus.
Connected to UCLALibrary/ursus#257

Add a route to get branding info

---

config/initializers/hyrax.rb

It's been bothering me that when I generated a list of URLs for @markmatney the URLs as produced by the system didn't work (in spite of the fact that universal viewer works fine). There was a mistake in the iiif URL, which this PR fixes. This also logs the request (at debug level) for easier problem diagnosis and performance measurement down the road.
Connected to UCLALibrary/amalgamated-samvera#272

Fix iiif url syntax for initial request

---

.rubocop.yml

Deleted this rule about the DescribeClass because it is unimportant.
```
Offenses:
spec/features/search_crawler_spec.rb:4:16: C: RSpec/DescribeClass: The first argument to describe should be the class or module being tested.
RSpec.describe "Search History Page", :clean do
^^^^^^^^^^^^^^^^^^^^^
137 files inspected, 1 offense detected
```
Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/287

Delete rule in rubocop

---

app/controllers/catalog_controller.rb
spec/features/search_crawler_spec.rb

**`config/schedule.rb:25`**
```
rake "blacklight:delete_old_searches[1]"
```
This PR will replace the need for this scheduled rake task.:
---
+ modified:   app/controllers/catalog_controller.rb
+ new file:   spec/features/search_crawler_spec.rb
Connected to UCLALibrary/amalgamated-samvera#287

Prevent  searches from being saved to the database

---

app/controllers/application_controller.rb
config/features.rb
spec/features/read_only_mode_spec.rb

which creates a safe window during which backups can be performed. 
When californica is in read-only mode it can still be searched  
and ursus will will be able to read from californica,  
but no changes can be made. 
+ There is a feature flipper that will turn the `read only` mode on and off
+ When read-only mode is in effect there is a banner telling Users why they can't add or edit records
---
+ modified:   app/controllers/application_controller.rb
+ new file:   config/features.rb
+ new file:   spec/features/read_only_mode_spec.rb

Implement a read-only mode

---

spec/features/read_only_mode_spec.rb

This fixes an intermittent CI failure that was throwing this error:
ActiveRecord::RecordNotFound:
Couldn't find Hyrax::CollectionType matching GID 'gid://californica/hyrax-collectiontype/9'

Fix intermittent CI failure

---

.rubocop.yml
.travis.yml
Gemfile
Gemfile.lock
spec/rails_helper.rb
spec/support/shared_contexts/workflow.rb
spec/system/create_work_spec.rb
spec/system/edit_collection_spec.rb
spec/system/edit_work_spec.rb
spec/system/import_and_show_work_spec.rb
spec/system/read_only_mode_spec.rb
spec/system/search_catalog_spec.rb
spec/system/search_crawler_spec.rb
spec/system/show_collection_spec.rb
spec/system/show_work_spec.rb

Convert to system tests instead of feature tests to give us more
stability around javascript testing and eliminate the need for database
cleaner, which has also been giving us intermittent problems.
This should make it easier to test the edit form.
Connected to https://github.com/UCLALibrary/californica/issues/456

Convert to system specs

---

app/forms/hyrax/californica_collections_form.rb
app/forms/hyrax/work_form.rb
app/views/records/edit_fields/_default.html.erb
spec/system/edit_work_spec.rb

Allow an Ark to be set via the new work form, but once an object has an
ark do not allow it to be edited from the form -- make it readonly.
Connected to #456

Ark values are not editable

---

app/importers/californica_mapper.rb
app/importers/csv_validator.rb

For validating the CSV file, we have required headers and allowed
headers.  I thought it was awkward that the required headers were in the
validator class, and the allowed headers were in the mapper class.  So,
I moved the required headers over to the mapper.  In the future, if a
developer needs to add a new column to the CSV file, they'll have to
edit the mapper, so it makes sense to put the required/allowed headers
near the place the new columns will go.
Connected to #481

Refactored code for readability

---

Gemfile
Gemfile.lock
app/actors/hyrax/actors/work_actor.rb
app/controllers/hyrax/dashboard/collections_controller_override.rb
app/lib/californica/id_generator.rb
app/models/collection.rb
spec/importers/actor_record_importer_spec.rb
spec/importers/californica_importer_spec.rb
spec/lib/californica/id_generator_spec.rb
spec/system/create_work_spec.rb
spec/system/import_and_show_work_spec.rb
spec/system/new_collection_spec.rb

If a work does not have an identifier, give it one based on its ark
value. Raise an error if it doesn't have an ark to use for this purpose.
Connected to #492

Assign primary identifiers based on ark

---

Dockerfile

This adds the newer nodejs, yarn, chromium, and chrome-driver packages
to the Dockerfile. These are already being used in the ursus Dockerfile.

Update Dockerfile to include chrome-driver deps

---

docker-compose.yml
docker/conf.d/mysql.cnf

I normally run the application on a Linux host
which doesn't require a VM. I tried running
californica on a Windows host (which uses a VM)
and needed to increase the default ram used by
the VM from 2GB to 8GB to get the test suite to run.
These changes will reduce the amount of memory used by
Fedora and MySQL so that users on non-Linux systems
will use less ram.

Reduce memory usage when running with Docker

---

Gemfile
Gemfile.lock

Upgrade Darlingtonia to 3.2.2, which fixes a bug where it was assuming
that the deduplication field would always be a multi-valued field.
Because we are using ARK as our deduplication field, and it is not
multi-valued, this was causing arks to be truncated in our import logs.
Connected to #537

Do not truncate the ARK in import logs

---

config/features.rb

Warn someone who is enabling read-only mode that they need to leave
their window open because they won't be able to create a new session
once read-only mode is on.
Connected to https://github.com/UCLALibrary/californica/issues/547

Add a warning to read-only mode

---

app/controllers/catalog_controller.rb
app/importers/actor_record_importer.rb
app/importers/californica_csv_cleaner.rb
app/lib/californica/id_generator.rb
app/models/collection.rb
app/models/solr_document.rb
app/models/ucla_metadata.rb
spec/importers/californica_importer_spec.rb
spec/indexers/collection_indexer_spec.rb
spec/indexers/work_indexer_spec.rb
spec/lib/californica/id_generator_spec.rb
spec/system/create_work_spec.rb
spec/system/import_and_show_work_spec.rb
spec/system/new_collection_spec.rb

This will give us an even b-tree distribution in fedora, which will
improve performance as the repository grows.
"ModeShape has been designed to efficiently handle a single node having a
large number (100K-200k) of child nodes out-of-the-box. However, if an
application stores a lot more nodes than that under a single parent,
performance in terms of latency and memory consumption starts to
decrease proportionally to the number of stored children."
Source:
https://docs.jboss.org/author/display/MODE40/Large+numbers+of+child+nodes#Largenumbersofchildnodes-Unorderedlargecollections
Since most (all?) of the UCLA ark identifiers start with the same
string, unless we reverse the ID values we'll have everything stored
under the same node in Fedora and hit performance issues when the system
reaches …

Reverse the ID value

---

spec/system/create_work_spec.rb

Depending on the environment you run tests in (and the drivers used
by capybara), tests for text on pages may or may not be case sensistive.
I've been getting the error:
Failures:
1) Create a Work a logged in user should text "Add New Work"
Failure/Error: expect(page).to have_content "Add New Work"
expected to find text "Add New Work" in v"Californica Switch language... ". (However, it was found 1 time using a case insensitive search.)
The text actually rendered to the page is "Add new work" instead of "Add New Work"

Use exact case in create_new_work spec

---

app/indexers/collection_indexer.rb
app/indexers/work_indexer.rb
app/lib/californica/id_generator.rb
app/models/collection.rb
app/models/work.rb
spec/factories/collections.rb
spec/indexers/collection_indexer_spec.rb
spec/indexers/work_indexer_spec.rb
spec/lib/californica/id_generator_spec.rb
spec/system/show_collection_spec.rb
spec/views/hyrax/base/_attribute_rows.html.erb_spec.rb

Given an ARK like 'ark:/abcdef/1234567', update the solr index to include
an `catalog_id_ssi` like 'abcdef-1234567' that can be used as the
primary identifer in blacklight applications like ursus.

Index a stripped down ARK for use in ursus

---

lib/tasks/ingest.rake

@andrewbenedictwallace I know I said we shouldn't use command line import anymore once the UI import was in place, and mostly I think that's true. However, having some rake commands for importing content makes launching a development environment much easier, and enables some tasks like performance benchmarking that would otherwise be more difficult. After some reflection, I decided to make sure that the ingest rake tasks still work.
Connected to #569

Update rake tasks to work with CsvImport class

---

docker-compose.yml

This seems to fix [CAL-582](https://jira.library.ucla.edu/browse/CAL-582), although only in docker.

run sidekiq in its own container

---

app/importers/californica_csv_cleaner.rb
spec/importers/californica_csv_cleaner_spec.rb

This is necessary so we can re-import works with the same ARK

CSV cleaner should destroy and eradicate objects CAL-582

---

app/importers/californica_csv_cleaner.rb

Previously, we were matching too broadly and sometimes eradicating
objects we shouldn't have matched on.

Only eradicate objects if the ark matches

---

app/controllers/catalog_controller.rb
spec/system/search_catalog_spec.rb

This uses the `mm` solr property for the
default search settings in the catalog controller
to make the default search behave like an AND
search with multiple terms.
Connected to CAL-589

Default to AND operator for search

---

app/controllers/hyrax/dashboard/collections_controller_override.rb
app/controllers/hyrax/works_controller.rb
spec/system/delete_work_spec.rb
spec/system/new_collection_spec.rb

Because we're using ark-based identifiers, we have to both destroy and
eradicate a work when it is deleted. Otherwise, it leaves a tombstone
resource behind in fedora and we can't re-create a new object with the
same ark.

Ensure we can delete and re-create works and collections

---

app/views/csv_imports/_form.html.erb

If a user tries to reference files anywhere other than `/opt/data`, it will not work. This change tells them that up front, to prevent any confusion should someone decide to try something non-standard.

Warn users that only /opt/data is valid for file import

---

app/services/californica/ingest_middleware_stack.rb

Josh, Andy, Bess, Mark and Lisa all discussed the import actor stack,
documented here:
https://docs.library.ucla.edu/pages/viewpage.action?spaceKey=CUP&title=Californica+CSV+Importer+Notes
We agreed the stripped down version mostly looked fine, except that we
should add the ApplyPermissionTemplateActor back in.

Restore ApplyPermissionTemplateActor

---

.rubocop.yml
Gemfile
app/importers/californica_csv_parser.rb
app/importers/californica_importer.rb
app/importers/californica_mapper.rb
app/importers/collection_record_importer.rb
app/models/collection.rb
spec/models/collection_spec.rb
spec/system/delete_work_spec.rb

* Turn off collection size calculation during ingest
* This sets us up for further work moving all collection re-indexing to the end of the ingest process
Improvement so far (because re-calculating the size of a collection gets more expensive the larger the collection gets, I would expect these numbers to be more dramatically different for LADNN than they are for Bennett):
Before:
I, [2019-05-01T11:40:36.807328 #24190]  INFO -- : event: finish_import, batch_id: 4, successful_record_count: 80, failed_record_count: 0, elapsed_time: 1656.7904343120172, elapsed_time_per_record: 20.709880428900213
After:
I, [2019-05-01T15:35:43.436054 #12308]  INFO -- : event: finish_import, batch_id: 5, successful_record_count: 80, failed_record_count: 0, elapsed_time: 1552.5210038349032, …

Remove collection size indexing to speed up ingest CAL-581

---

.rubocop.yml
app/importers/californica_mapper.rb
app/importers/collection_record_importer.rb
app/indexers/collection_indexer.rb
app/models/collection.rb
spec/system/show_collection_spec.rb

This builds on previous work that disabled collection size re-calculation during ingest. Now, we also turn off collection level solr indexing and collection level nested indexing during ingest, and then re-enable them once ingest is over.

CAL-581: move collection update index to end of ingest

---

config/deploy.rb
lib/tasks/fix_collection_type_labels.rake

It runs on deploy so it will run on production without needing sysadmin
intervention.
Before:
After:
During deploy:

Rake task to fix collection type labels

---

.env.sample
Gemfile
Gemfile.lock
app/jobs/hyrax/characterize_job.rb
app/lib/californica/is_valid_image.rb
config/initializers/characterization_service.rb
docker-compose.yml
spec/jobs/start_csv_import_job_spec.rb
spec/lib/californica/is_valid_image_spec.rb

This commit allows you to use an external
FITS Servlet for file characterization. To turn
it on, set the 'FITS_SERVLET_URL' environment varible
on your server before starting the server. This is
accomplished with overrides and prepends, so it won't
be possible for a FlipFlop feature to toggle this, because
you will need to restart your server.
The FITS servlet URL should be the full path to the FITS endpoint.
In the `docker-compose` environment this is at `http://fits:8080/fits` and the 
specs are run using the external fits servlet. On travis, the default FITS 
behavior (using the local version) is used. 
If the `FITS_SERVLET_URL` is not set, the server will use the default
FITS installation.
Connected to CAL-580

Use FITS Servlet

---

lib/tasks/read_only.rake

rake californica:read_only:on will put the system into read-only mode
rake californica:read_only:off will return it to normal operations
This will let us trigger read only mode from a cron job to automate
nightly backups.

Trigger read-only mode from the command line

---

app/importers/californica_mapper.rb
app/uploaders/csv_manifest_validator.rb
config/authorities/rights_statements.yml
spec/importers/californica_mapper_spec.rb
spec/uploaders/csv_manifest_validator_spec.rb

- maps missing rights statements values to 'unknown' on ingest (CAL-613)
- adds 'public domain' to rights_statements.yml (CAL-617 – out of sprint but trivial to add)

rights statements

---

app/actors/hyrax/actors/child_work_actor.rb
app/controllers/hyrax/child_works_controller.rb
app/forms/hyrax/child_work_form.rb
app/importers/actor_record_importer.rb
app/importers/californica_mapper.rb
app/models/child_work.rb
app/models/work.rb
app/views/hyrax/child_works/_child_work.html.erb
config/initializers/hyrax.rb
config/locales/child_work.de.yml
config/locales/child_work.en.yml
config/locales/child_work.es.yml
config/locales/child_work.fr.yml
config/locales/child_work.it.yml
config/locales/child_work.pt-BR.yml
config/locales/child_work.zh.yml
spec/factories/child_works.rb
spec/forms/hyrax/child_work_form_spec.rb
spec/importers/collection_record_importer_spec.rb
spec/jobs/mss_csv_import_job_spec.rb
spec/models/child_work_spec.rb
spec/models/collection_spec.rb
spec/support/shared_examples/ucla_metadata.rb
spec/system/create_child_work_spec.rb
spec/system/delete_child_work_spec.rb

* It has the same metadata attributes as a Work
* Refactor to share metadata examples
* It subclasses Work where ever possible
* It has an additional field, `in_works_ids`, containing its parent Work object

Create ChildWork object type

---

app/assets/markdown/importer_guide.md
app/importers/californica_mapper.rb
app/models/page_order.rb
app/uploaders/csv_manifest_validator.rb
db/migrate/20190514132636_create_page_orders.rb
db/schema.rb
spec/jobs/mss_csv_import_job_spec.rb
spec/models/page_order_spec.rb

During import, record a page's sequence in a PageOrder object. This will
make the page order for a given manuscript easy to recalcuate. Once a
manuscript import is complete, we'll query for all that mss's PageOrder
objects, sort them by sequence, and use that to set the order of the
pages.

Record page sequence in a PageOrder object

---

app/importers/californica_csv_parser.rb
spec/importers/californica_csv_parser_spec.rb

Validation at this level largely duplicates validation done in
CsvManifestValidator. CsvManifestValidator errors, however, are properly
interpreted as non-blocking warnings (when appropriate), and errors are
made visible to users. Validate errors from CalifornicaCsvParser, on the
other hand, always cause ingest to fail without user-visible messages.

remove all validators from CalifornicaCsvParser

---

app/uploaders/csv_manifest_validator.rb

This has not been entered for some collections, so it doesn't end up in the csvs. We already map missing values to 'unknown', so requiring the header isn't necessary.

CsvManifestValidator: make 'Rights.copyrightStatus' column optional CAL-631

---

.rubocop.yml
app/uploaders/csv_manifest_validator.rb
spec/fixtures/csv_import/csv_files_with_problems/invalid_values.csv
spec/uploaders/csv_manifest_uploader_spec.rb
spec/uploaders/csv_manifest_validator_spec.rb

Validates that files listed in a csv are present in CsvManifestValidator.manifest_uploader.model.import_file_path. If import_file_path is nil, no validation is performed and no warnings are given.
Unfortunately, when validation messages are displayed in the preview screen the CSVImport has not yet been saved to the database, and the unsaved object passed to CsvManifestValidator has manifest_uploader.model.import_file_path == nil. Thus, this functionality is not yet available.

validate files are present in CSV upload

---

spec/factories/file_sets.rb
spec/jobs/hyrax/characterize_job_spec.rb
spec/jobs/start_csv_import_job_spec.rb

Instead of testing Hyrax::CharacterizeJob via the CSV import process,
give it its own tightly focused test. This will make refactoring of the
CSV import process easier, and should make our test suite a little
faster.

Refactor Hyrax::CharacterizeJob spec

---

.rubocop.yml
app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb

Prerequisite of CAL-597, which (after CAL-584 creates the field) will map both AltTitle.other and AltTitle.translated to alternative_title.

Allow mapping of multiple ingest fields to a single californica field CAL-597

---

app/controllers/csv_imports_controller.rb
app/views/csv_imports/_start_import_form.html.erb
app/views/csv_imports/index.html.erb
app/views/hyrax/dashboard/sidebar/_tasks.html.erb
db/migrate/20190606181513_add_status_to_csv_import.rb
db/migrate/20190606192158_add_record_count_to_csv_import.rb
db/schema.rb
spec/factories/csv_imports.rb
spec/models/csv_import_spec.rb
spec/system/csv_import_status_reports_spec.rb
spec/system/import_from_csv_spec.rb

* Display all CsvImports, most recent first
* Put a link to that page on the admin dashboard
* Cache the number of records attached to a csv import on the object,
for faster display
* Give a CsvImport object a status field

CAL-604 report batch import status

---

config/environments/production.rb

`california-dev` is still running out of disk space because the logs. This will reduce the logging level in prod to error.

Decrease logging level in production

---

app/actors/hyrax/actors/work_actor.rb
app/controllers/csv_imports_controller.rb
app/importers/actor_record_importer.rb
app/jobs/csv_row_import_job.rb
app/views/csv_imports/show.html.erb
spec/factories/csv_rows.rb
spec/models/csv_row_spec.rb
spec/system/csv_import_status_show_spec.rb
spec/system/import_from_csv_spec.rb
spec/system/import_mss_from_csv_spec.rb

This PR represents the first part of CAL-605:
* Pass row id to import process so new background jobs can be tracked
* Use row_id instead of batch id and track ark in error messages
Importantly, this PR does NOT track the status of any background jobs a CSV row kicks off in deciding whether the row is complete or not.

Status report of the rows in a CSV Import

---

app/actors/hyrax/actors/work_actor.rb
app/controllers/csv_imports_controller.rb
app/importers/actor_record_importer.rb
app/jobs/csv_row_import_job.rb
app/models/csv_row.rb
app/views/csv_imports/show.html.erb
db/migrate/20190607170700_add_job_ids_to_csv_row.rb
db/schema.rb
spec/factories/csv_rows.rb
spec/jobs/csv_row_import_job_spec.rb
spec/models/csv_row_spec.rb
spec/system/csv_import_status_show_spec.rb
spec/system/import_from_csv_spec.rb
spec/system/import_mss_from_csv_spec.rb

* CsvRow should track what job ids have been queued, and which ones have
completed or errored.
* CsvRow should treat errors as an array, because there might be more than
one error reported for a given row.
* Instead of CsvRow status being a static string, it is determined by
looking at what background jobs have been queued, completed, and
errored.

Track background jobs ids in CsvRow

---

.rubocop.yml
app/controllers/hyrax/works_controller.rb
app/services/californica/child_work_service.rb
app/services/californica/manifest_builder_service.rb
app/views/hyrax/base/_representative_media.html.erb
app/views/hyrax/base/show.html.erb
app/views/manifest.json.jbuilder
spec/controllers/hyrax/works_controller_spec.rb
spec/services/californica/child_work_service_spec.rb
spec/services/californica/manifest_builder_service_spec.rb
spec/system/display_multipage_mss_spec_manual.rb
spec/system/edit_visibility_spec.rb
spec/views/manifest.json.jbuilder_spec.rb

The current views and libraries that generate the IIIF manifest
and display the UV interface assume that the the
`Work` is structured with an attached `FileSet` not additional
works. The first `Work` requires an attached `FileSet` or
it will not display.
The overrides the generation of the manifest so that
first `Work` will generate a manifest even if it  does
not have an image/FileSet attached to it.
This is done with a JBuilder view that the manifest
is genreated from.
Doing it this way it significantly faster. An Ethiopic manuscript
was taking 5 minutes to genrate a manifest. This is down to 1 minute.
That's still too slow, but it is still a large reduction.
Connected to CAL-638

Generate IIIF Manifest for works with ChildWorks

---

spec/system/edit_visibility_spec.rb

This should be functionally equivalent to https://github.com/UCLALibrary/californica/pull/633, but makes the code a bit cleaner by passing the ignore_query: true argument to the capybara assertion method, instead of stripping the query parameters with a regex.
I wouldn't have bothered, but I had already been looking at the issue and discovered this option around the same time @val99erie submitted her PR633.

use 'ignore_query: true' to ignore the locale part of the path in spec

---

.rubocop.yml
app/models/concerns/discoverable.rb
spec/jobs/inherit_permissions_job_spec.rb

I noticed this problem in the UI: when you change the visibility of a
work record, it gives you the option to apply those changes to all the
child records.  If you select 'yes' background jobs run to update all
the attached FileSet records.  But in some situations the resulting
visibility for the FileSets didn't match the parent work.
The problem was caused by an assumption in the hydra-access-controls
gem that caused it to incorrectly match on some access control records
that it was selecting for removal.  Because we are overriding visibility
in Californica, that assumption is no longer true.  I'll take a closer
look at the hydra-access-controls gem later and decide if we should file
a bug against it, but for now, overriding the "permissions_attributes="
method from that gem allows us to …

Fixed a problem with access controls in a FileSet record. Part of story 608.

---

config/initializers/hyrax.rb

We redefine the Hyrax::PermissionBadge::VISIBILITY_LABEL_CLASS constant
to add a new value to "visibility", but redefining a constant in ruby
will cause a warning message like:
already initialized constant Hyrax::PermissionBadge::VISIBILITY_LABEL_CLASS
This code undefines the constant before setting it to avoid that warning
message.

Undefine constant to avoid confusing warning message. Jira 608

---

.rubocop.yml
app/controllers/hyrax/works_controller.rb
docker-compose.yml
spec/controllers/hyrax/works_controller_spec.rb
spec/factories/works.rb

Cache the initial JSON manifest in Redis using
a key derived from the last modified time and the
id. That way the cache will be busted when the
work is modified.
This also sets the `Cache-Control` header for
the JSON response so that the browser also
caches the JSON for 24 hours (this can be
busted by using Shift-Refresh to reload
the page).
The commit also includes the changes that were made
to ursus to allow using `byebug` in the docker environment.
Connected to CAL-639

Initial caching

---

app/models/concerns/discoverable.rb
spec/models/concerns/discoverable_spec.rb

The bug was that when you edit a Work record in the browser and change
its visibility, and then apply the parent Work's visibility to the child
FileSet records, in some situations, the resulting visibility for the
FileSet records would be incorrect.

Fixed a bug with duplicate permissions. Jira 608

---

app/controllers/csv_imports_controller.rb
app/importers/actor_record_importer.rb
app/importers/californica_importer.rb
app/importers/collection_record_importer.rb
app/views/csv_imports/show.html.erb
config/routes.rb
spec/controllers/csv_imports_controller_spec.rb

This adds a route to see the ingest log for
a `csv_import`. This was previously using
a timestamp on the log file, but each `csv_import`
has an ID which can be discoverd through the UI.
Using the ID in the name will make it easier to
find the log, and allows for providing the ability
to view the log in the browser.

View logs on CSV Import status page

---

Gemfile
Gemfile.lock
app/jobs/application_job.rb
config/initializers/sidekiq.rb
config/routes.rb

This gem will give us more details about the status
of jobs in the sidekiq interface. When this is
installed there is a Statuses tab in the UI at the
top of the screen.

Add sidekiq-status gem

---

app/indexers/work_indexer.rb
spec/indexers/work_indexer_spec.rb

This field type can be used for alpha sorting on
strings.

Switch sort title to _ssort field type

---

app/controllers/hyrax/works_controller.rb
app/models/manifest.rb
db/migrate/20190618015737_create_manifests.rb
db/schema.rb
spec/factories/manifests.rb
spec/models/manifest_spec.rb

This caches the manifest in the db
instead of redis. This will allow
the manifests to be cached on disk
instead of just in-memory.

Persist manifest with db

---

config/locales/hyrax.en.yml
spec/system/locales.rb

There was an error in the yaml locale file
that was causing translation missing errors
in the admin interface. This removes the bad
char and checks that the admin interface isn't
saying 'translation missing'

Fix for translation missing errors

---

app/controllers/hyrax/works_controller.rb
db/migrate/20190618174001_add_cache_manifest_key_to_manifests.rb
db/schema.rb
spec/models/manifest_spec.rb

Don't use the primary key for storing the
key used to cache the manifests in the db.

Use a separate key for caching manifests

---

app/views/manifest.json.jbuilder

This changes the manifest to use the lambda from
config to generate the info.json url.

Use IIIF Info lambda from config

---

app/importers/record_importer.rb

Since parallel execution of CsvRowImportJob is currently not working, this executes it inline while we decide what to do.

disable parallel import of CSVRows

---

spec/views/manifest.json.jbuilder_spec.rb

This provides a more complete example in the
view spec for the IIIF Manifest. Instead
of checking for indvidual properties it compares
everything from a template at one time.

More complete example in manifest view spec

---

.rubocop.yml
spec/factories/works.rb
spec/views/manifest.json.jbuilder_with_child_spec.rb

There is a view spec for a work with a file attached.
This adds another spec that describes a manifest for
a work with ChildWorks.
This also adds some transient properties in the
Work factory to allow works with files or ChildWorks to
be easily created.

Additional spec for ChildWork manifest view

---

public/robots_allow.txt
public/robots_disallow.txt

I created two different robots.txt files, in addition to the default (empty) file, that will allow us to specify a configuration based on the server environment we're running the site in. This can be managed manually or via Ansible.

robots.txt files to allow or disallow web crawling

---

.rubocop.yml
app/auditors/californica_csv_auditor.rb
app/auditors/file_count_auditor.rb
lib/tasks/audit.rake
spec/auditors/californica_csv_auditor_spec.rb

Initially, the audit checks that each line of the CSV corresponds to a single record, and that record has a number of FileSets equal to the number of files in the "File Name" column of the CSV.

rake tasks to audit records based on CSV

---

app/importers/californica_csv_parser.rb
app/importers/californica_importer.rb
app/jobs/start_csv_import_job.rb

Errors have been causing imports to fail and restart, ingesting multiple copies of many filesets. Rescuing and logging these errors should help.

rescue errors in imports

---

app/assets/markdown/importer_guide.md
app/controllers/csv_imports_controller.rb
app/importers/californica_mapper.rb
app/views/csv_imports/_form.html.erb
app/views/csv_imports/_import_file_path.html.erb
spec/importers/californica_mapper_spec.rb
spec/system/import_from_csv_spec.rb
spec/system/import_mss_from_csv_spec.rb

The full path will be stored relative to the "Masters" directory at /opt/data/Masters. In production, this is mounted from the netapp.
If the input file name starts with "Masters/", it will be used as is. Otherwise, it will be prepended with "Masters/dlmasters/", in order to match the content of DLCS exports.

Require full path for "File Name"

---

app/importers/californica_importer.rb
app/importers/record_importer.rb
app/jobs/start_csv_import_job.rb
spec/importers/californica_importer_spec.rb
spec/system/import_and_show_work_spec.rb

Previously, log messages during ingest ended up in a few different files. This commit moves them to:
- Errors during a CsvRowImportJob end up in the associated csvrow object's "error_messages" field, which is stored in the database and visible in the dashboard.
- Errors that occur outside of any CsvRowImportJob get logged in the ingest_X.log file (also with info-level messages), which is written to the filesystem and visible from the dashboard.

Streamline ingest logging

---

config/initializers/hyrax.rb

Edit page failed to render visibility badge in dev (not on servers)
The work edit page failed to render due to an error related to the "discovery"-level visibility badge.
This happened only in development, not in production. That's because this line was invoked in production:
https://github.com/UCLALibrary/californica/blob/a6e251a1692aecb073a9928d6d6f1c91e9b38700/config/initializers/hyrax.rb#L13
But per this discussion:
https://stackoverflow.com/questions/8895103/how-can-i-keep-my-initializer-configuration-from-being-lost-in-development-mode
it ran once in development but then reset on subsequent requests.
---
+ modified: `config/initializers/hyrax.rb`

Fix - Edit page fails to render visibility badge in dev (not on servers)

---

app/assets/markdown/importer_guide.md
app/importers/actor_record_importer.rb
spec/importers/actor_record_importer_spec.rb

This change raises an AttributeError instead, with a useful message that gets stored in the CsvRowImport database and displayed on the dashboard.

On ingest, don't create new record if the title starts with "DUPLICATE"

---

app/controllers/hyrax/works_controller.rb
app/services/californica/manifest_builder_service.rb
app/views/manifest.json.jbuilder
config/features.rb
spec/services/californica/manifest_builder_service_spec.rb
spec/views/manifest.json.jbuilder_spec.rb
spec/views/manifest.json.jbuilder_with_child_spec.rb

Previously, building IIIF manifests could only be done in the context of an HTTP request, from which a URL was extracted for use in IIIF identifiers. This commit derives those identifiers from other sources so that manifests can be generated outside the HTTP request cycle, for example immediately upon ingest.

Remove dependencies on HTTP request for IIIF manifest generation.

---

default.env
docker-compose.yml
docker.env

This moves most of the environment variables from docker.env to default.env, changing values specific to our docker setup to values that allow a native-running rails process to connect to services running in docker containers.
To run natively, run `ln -s default.env .env` to create a symlink.

Configure .env files so app can be run natively

---

app/indexers/collection_indexer.rb
app/indexers/work_indexer.rb
app/services/californica/manifest_builder_service.rb
app/views/manifest.json.jbuilder
default.env
spec/services/californica/manifest_builder_service_spec.rb

- Creates a helper function which generates IIIF links from `access_copy`, determining whether they should point to the old Cantaloupe or the new IIIF server.
- Uses this helper function in generating manifests.
- Uses the helper function for thumbnails.

Use new IIIF service for manifests and thumbnails

---

app/forms/hyrax/work_form.rb
app/views/records/edit_fields/_language.html.erb
spec/forms/hyrax/child_work_form_spec.rb
spec/forms/hyrax/work_form_spec.rb
spec/system/edit_collection_spec.rb
spec/system/edit_work_spec.rb

- Changes the 'Language' widget to a multiselect.
- Removes the field 'based_near', a hyrax default that we aren't using
- Moves preservation_copy and access_copy above the fold.

Fixes to Work and Collection forms

---

app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb

This fixes a bug that prevented images from displaying for newly-imported works. The field access_copy should eventually be filled from a new CSV column created by bucketeer. This column is not yet ready, however, so for now we will continue to populate it from "File Name".

fix to populate access_copy from File Name

---

app/services/californica/manifest_builder_service.rb
spec/services/californica/manifest_builder_service_spec.rb

This allows manifests to be created outside of the HTTP request cycle.

generate IIIF manifest from ManifestBuilderService

---

Gemfile
Gemfile.lock
app/services/californica/manifest_builder_service.rb
spec/services/californica/manifest_builder_service_spec.rb
spec/spec_helper.rb

If IIIF_MANIFEST_URL is set, submits the manifest to the service at that location in addition to saving it locally.

Cache IIIF manifests to the Manifest Store Service

---

.rubocop.yml
app/jobs/csv_row_import_job.rb
app/views/csv_imports/show.html.erb
db/migrate/20190830171825_add_ingest_duration_to_csv_row.rb
db/schema.rb
spec/system/import_from_csv_spec.rb

https://jira.library.ucla.edu/browse/CAL-752
modified:   .rubocop.yml
modified:   app/jobs/csv_row_import_job.rb
modified:   app/views/csv_imports/show.html.erb
new file:   db/migrate/20190830171825_add_ingest_duration_to_csv_row.rb
modified:   db/schema.rb
modified:   spec/system/import_from_csv_spec.rb

Add ingest duration to csv rows to record ingest time per row

---

app/models/solr_document.rb
app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
config/features.rb
spec/models/solr_document_spec.rb

Feature is wrapped in a Flipflop toggle. If the flag is disabled, or if the 'iiif_manifest_url' field is empty, then defaults to serving a manifest directly from californica.
The flag is disabled by default, because we need to wait for CORS headers to be set on the service's end before the feature will work.

Use manifests from the manifest-store service

---

app/controllers/hyrax/works_controller.rb
app/services/californica/manifest_builder_service.rb
app/views/manifest.json.jbuilder
spec/views/manifest.json.jbuilder_spec.rb
spec/views/manifest.json.jbuilder_with_child_spec.rb

viewingHint is *not* being included at this time, as Universal Viewer does not correctly match paired pages when there are extra initial images (e.g. an exterior photo).

include viewingDirection in IIIF manifest

---

.gitignore
spec/spec_helper.rb

this enables it to be run with the `--only-failures` and `--next-failure` flags.

configure rspec to persist failures

---

app/assets/stylesheets/_ingest_metrics.scss
app/assets/stylesheets/_variables.scss
app/assets/stylesheets/application.css
app/assets/stylesheets/hyrax.scss
app/controllers/csv_imports_controller.rb
app/views/csv_imports/show.html.erb
spec/system/csv_import_status_show_spec.rb
spec/system/import_from_csv_spec.rb

Connected to [CAL-753](https://jira.library.ucla.edu/browse/CAL-753)
+ min
+ max
+ mean
+ median
+ standard deviation
---
+ new file:   app/assets/stylesheets/_ingest_metrics.scss
+ modified:   app/assets/stylesheets/_variables.scss
+ modified:   app/assets/stylesheets/application.css
+ modified:   app/assets/stylesheets/hyrax.scss
+ modified:   app/controllers/csv_imports_controller.rb
+ modified:   app/views/csv_imports/show.html.erb
+ modified:   spec/system/csv_import_status_show_spec.rb

CAL-753 Display ingest metrics on csv_import_show page

---

Gemfile
Gemfile.lock

this enables the rspec suite to use the spring preloader, which is already being used by the development server.
Turns this:
```
californica$ bundle exec rspec spec/jobs/create_manifest_job_spec.rb
Randomized with seed 21165
CreateManifestJob
calls the ManifestBuilderService
Top 1 slowest examples (0.30446 seconds, 75.1% of total time):
CreateManifestJob calls the ManifestBuilderService
0.30446 seconds ./spec/jobs/create_manifest_job_spec.rb:13
Finished in 0.40524 seconds (files took 21.49 seconds to load)
1 example, 0 failures
Randomized with seed 21165
```
Into this:
```
californica$ bundle exec spring rspec spec/jobs/create_manifest_job_spec.rb
Running via Spring preloader in process 77178
Randomized with seed 39080
CreateManifestJob
calls the ManifestBuilderService
Top 1 slowest …
```

add spring-commands-rspec

---

app/importers/californica_importer.rb
app/jobs/create_manifest_job.rb
spec/jobs/create_manifest_job_spec.rb

Right now it's executed synchronously with "perform_now" so that its timing will be tracked as part of the parent job. In the future it will be executed asynchronously.

Wrap manifest creation in job

---

app/jobs/application_job.rb
spec/jobs/application_job_spec.rb

Adds infrastructure to ApplicationJob such that its subclasses may define a method 'deduplication_key', with the result that if a job has already been enqueued with the same deduplication_key, it will not be enqueued again.

Allow deduplicated jobs

---

default.env
docker-compose.yml

- correct SOLR_URL when running natively against docker
- mount a docker volume over /californica/log to avoid permission errors

Fixes for docker

---

.rubocop.yml
app/jobs/create_manifest_job.rb
app/jobs/reindex_item_job.rb
app/models/csv_import_task.rb
db/migrate/20191011173814_create_csv_import_tasks.rb
db/schema.rb
default.env
docker-compose.yml
spec/actors/californica/manifest_actor_spec.rb
spec/factories/csv_import_tasks.rb
spec/jobs/create_manifest_job_spec.rb
spec/jobs/reindex_item_job_spec.rb
spec/models/csv_import_task_spec.rb

Adds support for future re-parallelizing of ingest:
- CsvImportTask model to track durations of the tasks that get deferred to the end of ingest
- ReindexItemJob to reindex a collection (or in future a Work) after all members have been imported.
- Duration tracking for ReindexItemJob and CreateManifestJob
- Deduplication of ReindexItemJob and CreateManifestJob, so we can perform_later these every time a child is ingested but they will only be enqueued once.
None of this actually gets used yet.

Support for re-parallelizing ingest

---

.rubocop.yml
app/jobs/create_manifest_job.rb
app/jobs/csv_row_import_job.rb
app/jobs/reindex_item_job.rb
app/views/csv_imports/show.html.erb
db/migrate/20191025023335_add_start_and_end_timestamps_to_csv_row.rb
db/schema.rb
spec/models/csv_import_task_spec.rb
spec/system/csv_import_status_show_spec.rb
spec/system/import_from_csv_spec.rb

Connected to: [CAL-811](https://jira.library.ucla.edu/browse/CAL-811)
+ The CsvImport show page shows the start and end times of the CsvImport as a whole
+ The table of CsvRows has columns for start and end times of each CsvRow
on the dev server
---

CAL-811 Add start and end timestamps to CsvRow status page

---

.rubocop.yml
app/controllers/csv_imports_controller.rb
app/importers/californica_importer.rb
app/importers/record_importer.rb
app/jobs/create_manifest_job.rb
app/jobs/csv_row_import_job.rb
app/jobs/reindex_item_job.rb
app/models/csv_row.rb
spec/importers/californica_importer_spec.rb
spec/importers/record_importer_spec.rb
spec/models/csv_import_task_spec.rb
spec/models/csv_row_spec.rb

Ensures that, in a situation where a CSV Import job fails and is restarted by sidekiq, CsvRows that have already been ingested are not ingested again.

don't repeat CsvRows when re-running CalifornicaImporter

---

.rubocop.yml
app/controllers/csv_imports_controller.rb
app/importers/californica_importer.rb
app/jobs/start_csv_import_job.rb
app/views/csv_imports/show.html.erb
db/migrate/20191107174854_add_start_time_to_csv_imports.rb
db/migrate/20191107174929_add_end_time_to_csv_imports.rb
db/schema.rb
docker-compose.yml
spec/importers/californica_importer_spec.rb

Previously, if the job failed and was restarted by sidekiq, only the elapsed time of the last run was recorded. This PR instead records the start time of the *first* run to the database, and uses this to compute elapsed time.

Measure CsvImport time from when the job first begins

---

Dockerfile

Changes the package used to install the mysql client library in docker image. This is required to use the mysql2 gem with the latest debian packages.

change mariadb-client to default-libmysqlclient-dev

---

app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb

Although we have been intending to disable collection reindexing, this has actually only happened while processing the collection row. As a result, it was still very inefficient to ingest csvs that did not begin with a collection.

disable collection reindexing when ingesting children

---

app/assets/markdown/importer_guide.md
app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb

Connected to [CAL-750](https://jira.library.ucla.edu/browse/CAL-750)
"Description.contents" has been removed from Summary so it doesn't map to Summary anymore.
We need to Add the "Contents note" before we do [CAL-750](https://jira.library.ucla.edu/browse/CAL-750). https://jira.library.ucla.edu/browse/CAL-781
---
+ modified: `app/assets/markdown/importer_guide.md`
+ modified: `app/importers/californica_mapper.rb`
+ modified: `spec/importers/californica_mapper_spec.rb`

Remove "Description.contents" from Summary

---

app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb

[Cal 878](https://jira.library.ucla.edu/browse/CAL-878)
Enable the ability to ingest items that belong to more than one collection.
Acceptance criteria:

CAL-878 Add items to multiple collections on ingest

---

app/indexers/collection_indexer.rb

Prevent the collection title from sometimes displaying the prefix "Ingesting now:" in front of the collection title.
- Acceptance Criteria:
[x] remove code that changes the title during the ingest process (both the code that puts "ingesting now" and the code that removes it when done)
[x] Investigate why the removal part of that code is not being triggered and document.write tickets

Remove code that prepends "Ingesting now" to collection title

---

app/indexers/collection_indexer.rb
app/indexers/work_indexer.rb
spec/indexers/collection_indexer_spec.rb
spec/indexers/work_indexer_spec.rb

Previously, the field title_ssort was used, breaking sorting in Ursus

Index to title_alpha_numeric_ssort

---

app/importers/californica_mapper.rb

Connected to [CAL-913](https://jira.library.ucla.edu/browse/CAL-913)
---
This is already done for two other fields: **`subject`** and **`named_subject`**.
---
**Acceptance Criteria:**
**Files**
`app/importers/californica_mapper.rb`
**Verified**
An import was performed to verify that $ (`$z`) characters are removed. Details: [CAL-913](https://jira.library.ucla.edu/browse/CAL-913).
---
**Screenshot**

CAL-913 Strip MARC subfields from all ingested values

---

spec/system/create_child_work_spec.rb
spec/system/edit_visibility_spec.rb
spec/system/import_from_csv_spec.rb
spec/system/new_collection_spec.rb

The tests that keep failing:
+ system/import_from_csv_spec.rb:16 - visit new_csv_import_path
+ 7x - system/new_collection_spec.rb:21 - 
+ 2x - system/new_collection_spec.rb:26 - 
+ system/csv_import_status_show_spec.rb:24 - 
+ 3x - system/create_child_work_spec.rb:25 - 
+ system/search_crawler_spec.rb:13 - 
+ 2x - system/edit_visibility_spec.rb:21
+ 7x - system/edit_visibility_spec.rb:39 - 
---
I added some tests with Cabybara's waiting finder, `have_content`,  
which will will **look for the content and retry** if it is not there yet. 
The tests won't progress if this fails.
---
https://engineering.gusto.com/eliminating-flaky-ruby-tests/
>>Avoid dangerous methods that do not wait
>>
>>visit(path) / current_path
>>all(selector) / first(selector)
>>Accessors: text, value, title, etc
>> …

Comment out Flaky Tests

---

app/controllers/catalog_controller.rb
app/models/ucla_metadata.rb

Connected to [URS-904](https://jira.library.ucla.edu/browse/URS-904)
+ Adds the :facetable to uniform_title in the `ucla_metadata.rb` file to make the field click to the search in Ursus
+ Adds some comments for clarity in the `catalog_controller.rb`
---
modified:  
+ `app/controllers/catalog_controller.rb`
+ `app/models/ucla_metadata.rb`

URS-904 Hyperlink "Uniform title" values in Item Page

---

app/controllers/hyrax/child_works_controller.rb
app/controllers/hyrax/dashboard/collections_controller_override.rb
app/controllers/hyrax/works_controller.rb
spec/system/delete_work_spec.rb

Connected to [CAL-948](https://jira.library.ucla.edu/browse/CAL-948) 
- Reverts destroy method from this [commit](https://github.com/UCLALibrary/californica/commit/df650ea79360e6e977b1cb51be18c14f70bdefbf#diff-2465ed21125db5507b630f05bc2acbee)

CAL-948 Revert delete button behavior

---

app/importers/actor_record_importer.rb
app/importers/collection_record_importer.rb
app/jobs/csv_row_import_job.rb

Connected to [CAL-949](https://jira.library.ucla.edu/browse/CAL-949) and [CAL-956](https://jira.library.ucla.edu/browse/CAL-956)
---
Automatically ingest CSVs that have Collections and/or Works with tombstones instead of contacting the DIIT Apps team for manual intervention.
---
**Acceptance Criteria:**
**Files**
`app/importers/actor_record_importer.rb`
`app/importers/collection_record_importer.rb`
**Verified**
Several collection and/or works were ingested, deleted and re-ingested to verify satisfactory operation in the presence of tombstones. The following behavior is encountered when re-ingesting:
_Collection_
Re-ingesting the whole collection (collection and all works) is required so that the system can associate the works with the re-ingested collection.
- After a collection is …

Cal 949 catch tombstone exceptions on re ingest2

---

app/controllers/catalog_controller.rb
app/models/ucla_metadata.rb
app/views/hyrax/base/_attribute_rows.html.erb
config/locales/hyrax.en.yml
spec/system/import_and_show_work_spec.rb

Connected to [URS-955](https://jira.library.ucla.edu/secure/RapidBoard.jspa?rapidView=131&view=detail&selectedIssue=URS-955)
Acceptance criteria:

URS 955: Ursus: add "Repository" field to browse facets

---

app/indexers/collection_indexer.rb
app/indexers/work_indexer.rb
spec/indexers/collection_indexer_spec.rb
spec/indexers/work_indexer_spec.rb

updates thumbnail indexing logic to ensure that:
- a fully formed IIIF url (with parameters) is passed as is, without spurious parameters added
- if the IIIF resource is improperly formatted, we don't index it (Ursus will use the default icon)

quick fix for thumbnail logic

---

app/importers/actor_record_importer.rb
app/importers/californica_importer.rb
app/jobs/csv_row_import_job.rb
app/jobs/start_csv_import_job.rb
app/lib/californica/deleter.rb
config/initializers/rollbar.rb

- For errors that are logged to mysql (in the CsvImport and CsvRow models), also send to Rollbar so devs can see a full stack trace.
- When MySQL issues happen (when prevent updating the CsvImport / CsvRow objects), wait 10 minutes and try again.
- When CSV Import restarts, import all rows that don't have status 'complete' or 'pending finalization'.

Improve Error handling on CSV import

---

docker-compose.yml

Northwestern University library removed their fcrepo image from dockerhub, so we've pushed an old copy into our own organization.

fork nulib/fcrepo4 docker image to uclalibrary/fcrepo4

---

app/models/solr_document.rb
spec/models/solr_document_spec.rb

Connected to [APPS-2357](https://jira.library.ucla.edu/browse/APPS-2357)
CSVs with no content invoke the Universal Viewer but are displayed with no image.

fix: APPS-2357_wrong-image-associated-with-uploaded-metadata

---

app/lib/californica/deleter.rb
lib/tasks/delete.rake

This PR will update the delete rake task to support the following changes:
- A work will be deleted if all its child items are deleted.
- A collection will be deleted if all its work items are deleted

feat: APPS-2387 update delete rake task

---

.rubocop.yml
app/lib/californica/deleter.rb
lib/tasks/delete.rake

Connected to https://uclalibrary.atlassian.net/browse/APPS-2387

fix: add work count and childworkcount to rollbar logs
