README.md

This is some quick information about the relationship between Tenejo, Hyrax, and
this application.

Add information about Tenejo and Hyrax to README.md

---

config/blacklight.yml
config/deploy.rb
config/deploy/cd.rb
config/solr.yml

See guide at
https://curationexperts.github.io/ansible-samvera/capification.html

Capification

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb
db/seeds.rb

I will document the login and password in the wiki.
Closes #11

Add a default admin user

---

app/models/work.rb
spec/models/work_spec.rb

Add property to work
Add test
Connected to #48

Add extent to work model

---

app/ingest/mods_mapper.rb
spec/ingest/mods_mapper_spec.rb
spec/ingest/mods_xml_parser_spec.rb

Inform parser about extent
Add extent to MODS mapper
Add extent to mapper fields in test
Connected to #48

Add extent to importer

---

.rubocop.yml
app/importers/californica_csv_parser.rb
app/importers/californica_mapper.rb
lib/tasks/ingest.rake
spec/importers/californica_csv_parser_spec.rb
spec/importers/californica_mapper_spec.rb

Adds a CSV Importer and rake task.

Implement a CSV importer

---

config/deploy/californica-test.rb

This is the first Red Hat/UCLA deploy target.

Add deploy file for californica-test server

---

Gemfile.lock

Downgrade qa to avoid withdrawn version

---

Capfile
Gemfile
Gemfile.lock
config/schedule.rb

Start with two regular cleanup jobs:
* Cleanup saved blacklight searches
* Cleanup /tmp from old derivatives
Connected to #120

Set up application to run cron jobs

---

.env.sample
lib/tasks/ingest.rake

* Rename it (we're reingesting, not reindexing)
* Re-use already existing csv import logic
* Remove dead MODS importer task
* Ensure reingest task picks up local environment
for library loading
Connected to #156

Refactor reingest rake task

---

app/controllers/catalog_controller.rb
app/models/work.rb
config/locales/blacklight.en.yml
config/locales/simple_form.en.yml
spec/models/work_spec.rb

This adds the normalized date term to the model
and configures the label and facet/search options
as specified in the issue.
Connected to #152

Add normalized date to model

---

config/schedule.rb

Fix cron job so it calls the re-named reingest task

---

app/models/work.rb
config/locales/simple_form.en.yml
spec/models/work_spec.rb

This commit adds the rights_attribute term to the
model and changes the labels as specified in the
issue.
Connected to #145

Add the rights holder term

---

app/controllers/catalog_controller.rb
app/models/work.rb
spec/models/work_spec.rb

This commit adds the caption vocab term
to the data model and allows it to be facted.
Connected to #178

Add caption term

---

app/controllers/catalog_controller.rb
app/models/work.rb
spec/models/work_spec.rb

Added location field to a Work. Connected to #101

---

config/deploy/californica-dev.rb

Adding a deploy file so we can do deployments to the UCLA sandbox server `californica-dev.library.ucla.edu`

Configuration to depoy to ucla sandbox server

---

config/deploy/californica-stage.rb

Including a deploy file for the californica-stage server
Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/71

Deploy configuration for californica-stage server

---

app/forms/hyrax/work_form.rb
config/locales/hyrax.en.yml
spec/features/create_work_spec.rb
spec/features/edit_work_spec.rb

Make sure new fields are on edit form. Story #207

---

app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb
spec/tasks/ingest_spec.rb

Work setting up publisher object was done in #106 
Connected to #107

Map `Publisher.publisherName` during CSV import

---

app/views/hyrax/base/_attribute_rows.html.erb

Remove duplicate extent field from the attribute_rows template

---

app/services/reindex_service.rb
lib/tasks/ursus.rake
spec/services/reindex_service_spec.rb

I added a method to delete all the solr docs from the 2nd solr.
I refactored the reindex method to pull out code that is needed in both
methods.
I updated the rake task to clean out the ursus solr before reindex.

Clean Ursus solr before reindexing. Connected to #214

---

app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb

Connects UCLALibrary/amalgamated-samvera#48

Hard code a language value for the LADNN collection

---

.env.sample
db/seeds.rb

Make admin email configurable by environmental variable too.
Connected to: #45

Add an admin email

---

config/authorities/rights_statements.yml
spec/features/create_work_spec.rb
spec/features/edit_work_spec.rb

- Connects to #243
- Remove default Hyrax copyright statements
- Add UCLA LADNN copyright statement value

Revise copyright statements to match UCLA LADNN values

---

app/controllers/catalog_controller.rb
app/models/work.rb
config/locales/blacklight.en.yml
spec/features/import_and_show_work_spec.rb

Make Californica facets match the acceptance
criteria in https://github.com/UCLALibrary/californica/issues/267
Connected to https://github.com/UCLALibrary/californica/issues/267

Californica facets

---

app/controllers/catalog_controller.rb
app/renderers/hyrax/renderers/rights_statement_attribute_renderer.rb
spec/features/import_and_show_work_spec.rb

Some style problems crept in while travis integration was down.

Rubocop style fixes

---

config/locales/blacklight.en.yml
config/locales/hyrax.en.yml
config/locales/simple_form.en.yml
spec/features/edit_work_spec.rb

Edit normalized date label

---

.rubocop.yml
app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb
spec/tasks/ingest_spec.rb

Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/165

Remove marc fields from named subject

---

config/locales/hyrax.en.yml

On work show page, changed 'Subject' label to 'Subjects'. Story #272

---

app/indexers/work_indexer.rb
spec/indexers/work_indexer_spec.rb

Connected to https://github.com/UCLALibrary/ursus/issues/57

Add a human-readable rights statement to solr index for display in Ursus. Story UCLALibrary/ursus#57

---

app/forms/hyrax/work_form.rb
spec/features/edit_work_spec.rb
spec/forms/hyrax/work_form_spec.rb

- Add photographer to list of required fields in work_form_spec
- Add photographer to list of fields in work_from
- Connects #281

Add photographer to list of fields in work_form

---

.rubocop.yml
app/controllers/catalog_controller.rb
spec/features/search_catalog_spec.rb

Set search fields. Story #268

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

Add coverall gem to track our test coverage over time.
---
+ modified:   Gemfile
+ modified:   Gemfile.lock
+ modified:   spec/spec_helper.rb

Add Coverall

---

.rubocop.yml
lib/tasks/derivatives.rake

Rake task to regenerate derivatives for a certain work. Story #304

---

LICENSE

Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/179

Revise copyright statement in License

---

Gemfile
Gemfile.lock

Connected to UCLALibrary/californica#321

Replace `sass-rails` with `sassc-rails`

---

app/controllers/catalog_controller.rb
config/locales/blacklight.en.yml
spec/features/import_and_show_work_spec.rb

Change label for named_subject to Names, revise tests to match

---

config/locales/californica.en.yml

Rename app from Samvera to Californica

---

app/assets/stylesheets/_feedback_link.scss
app/assets/stylesheets/_variables.scss
app/assets/stylesheets/hyrax.scss
app/views/shared/_footer.html.erb

- port feedback link code from Ursus (see
https://github.com/UCLALibrary/ursus/pull/105 for more details)
Connected to #315

Add feedback link code from Ursus for Californica

---

app/assets/stylesheets/application.css

Remove the background for the facet-panel-collapse div

---

.travis.yml

Based on a tagged release, this will trigger a `curl` command to execute a jenkins deploy. 
Required by UCLALibrary/amalgamated-samvera#115

Support for deploying tagged releases to stage server via jenkins

---

config/redis.yml

(needed for my docker-compose.yml to work)

Use REDIS_HOST and REDIS_PORT, if set, in dev and test 

---

Gemfile.lock

Connected to https://github.com/UCLALibrary/californica/issues/351

Update actionpack to fix dependency issues

---

config/environments/production.rb

See https://github.com/svenfuchs/i18n/releases/tag/v1.1.0 for
details.

Fix locale fallback to work with latest i18n release

---

lib/tasks/reindex.rake

We want to be able to reindex the Works with the single value ark field `ark_ssi`
---
+ new file:   lib/tasks/reindex.rake

Add a rake task to allow reindexing of the Works

---

README.md
app/importers/californica_importer.rb
lib/tasks/ingest.rake

Use the COLLECTION_ID environment variable to specify which collection
newly ingested works should be added to.
Connected to #395

Add works to a collection via rake

---

app/indexers/year_parser.rb

Connected to https://github.com/UCLALibrary/californica/issues/393

Don't report metadata errors to Rollbar

---

.rubocop.yml
app/controllers/hyrax/dashboard/collections_controller_override.rb
app/forms/hyrax/californica_collections_form.rb
config/application.rb
spec/features/edit_collection_spec.rb

Add UCLA metadata fields to collection edit form

---

Gemfile
Gemfile.lock

connected to #429 
(but only incidentally)

add xray to Gemfile

---

app/models/collection.rb
spec/factories/collections.rb
spec/models/collection_spec.rb

Find or create a Collection using ARK

---

app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb

connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/231

231-marc-codes

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
app/models/ucla_metadata.rb
app/presenters/hyrax/californica_collection_presenter.rb
app/presenters/hyrax/work_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
spec/factories/works.rb
spec/features/show_collection_spec.rb
spec/features/show_work_spec.rb
spec/models/work_spec.rb

The ark appears on work show pages
The ark appears on collection show pages
Connected to #456

Add an 'ark' property to the UCLA data model

---

Gemfile
Gemfile.lock

Sort Gemfile alphabetically to make it easier to navigate

---

README.md

Update docs to explain /opt/data/Masters mount.

---

app/forms/hyrax/californica_collections_form.rb
spec/system/edit_collection_spec.rb
spec/system/new_collection_spec.rb

For now, allow editing of ark... I will fix this in a future PR
Connected to #456

Add ark as a required field to new collection form

---

.rubocop.yml
app/controllers/catalog_controller.rb
app/forms/hyrax/californica_collections_form.rb
spec/system/edit_collection_spec.rb
spec/system/new_collection_spec.rb
spec/system/search_catalog_spec.rb

Search for ark

---

app/importers/actor_record_importer.rb
app/importers/californica_importer.rb
app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb
spec/system/import_and_show_work_spec.rb

Import ark value to the ark field
Deduplicate records based on their ark field
Connected to https://github.com/UCLALibrary/californica/issues/457
Connected to https://github.com/UCLALibrary/californica/issues/458

Import and deduplicate with ark

---

README.md

Add read-only mode emergency recovery procedure to README

---

app/actors/hyrax/actors/work_actor.rb

@mark-dce This is the refactor we discussed. LMK if this looks okay to you.

Refactor to override as little of the BaseActor as possible

---

config/locales/hyrax.en.yml
spec/system/edit_work_spec.rb

Connected to https://github.com/UCLALibrary/californica/issues/439

Change label for based_near from 'Location' to 'Based Near'

---

.rubocop.yml
app/controllers/csv_imports_controller.rb
app/models/ability.rb
app/models/csv_import.rb
app/uploaders/csv_manifest_uploader.rb
app/uploaders/csv_manifest_validator.rb
app/views/csv_imports/_form.html.erb
app/views/csv_imports/_start_import_form.html.erb
app/views/csv_imports/index.html.erb
app/views/csv_imports/new.html.erb
app/views/csv_imports/preview.html.erb
app/views/csv_imports/show.html.erb
app/views/hyrax/dashboard/sidebar/_tasks.html.erb
config/routes.rb
db/migrate/20190404170827_create_csv_imports.rb
db/migrate/20190404170828_add_manifest_to_csv_imports.rb
db/schema.rb
spec/controllers/csv_imports_controller_spec.rb
spec/factories/csv_imports.rb
spec/fixtures/csv_import/csv_files_with_problems/extra_headers.csv
spec/fixtures/csv_import/csv_files_with_problems/missing_title_header.csv
spec/fixtures/csv_import/import_manifest.csv
spec/models/csv_import_spec.rb
spec/rails_helper.rb
spec/routing/csv_imports_routing_spec.rb
spec/uploaders/csv_manifest_uploader_spec.rb
spec/uploaders/csv_manifest_validator_spec.rb

* Be able to upload a CSV via the browser
* Validate the CSV against Californica's required fields
* Raise an error if there are missing required headers
* Raise a warning if there are unrecognized headers
Connected to #503

Validate CSV via browser uploaded file

---

app/assets/markdown/importer_guide.md
app/helpers/importer_documentation_helper.rb
spec/views/importer_documentation/guide.html.erb_spec.rb

Connected to https://github.com/UCLALibrary/californica/issues/511

Add a styled label for required fields in CSV docs

---

.rubocop.yml
app/importers/californica_csv_cleaner.rb

Connected to https://github.com/UCLALibrary/californica/issues/528
items aren't getting deleted by ark - perhaps using "local identifier" will work?

Fix clean tasks

---

config/locales/hyrax.en.yml

add terms to hyrax.en.yml

---

spec/rails_helper.rb
spec/system/import_from_csv_spec.rb

Test for enqueued job on CSV import system spec
Connected to https://jira.library.ucla.edu/browse/CAL-406

CAL-406 Allow background jobs to run in system specs

---

config/initializers/hyrax.rb

Only whitelist /opt/data for file attachments

---

Dockerfile

This was causing problems, I thought I fixed it a long time ago.

don't `bundle install` with `--freeze`

---

app/importers/californica_csv_parser.rb

Since many duplicate items are likely to be added to these collections,
this should be good for both readability and performance.

Use Sets to track changed items in CalifornicaCsvParser

---

app/controllers/catalog_controller.rb
app/importers/californica_mapper.rb
app/indexers/work_indexer.rb
app/renderers/hyrax/renderers/language_renderer.rb
app/services/californica/language_service.rb
app/uploaders/csv_manifest_validator.rb
app/views/hyrax/base/_attribute_rows.html.erb
config/authorities/languages.yml
config/initializers/hyrax.rb
spec/importers/californica_mapper_spec.rb
spec/indexers/work_indexer_spec.rb
spec/renderers/language_renderer_spec.rb
spec/system/show_collection_spec.rb

For example, the underlying values 'zxx' and 'tlh' display as:

use MODS vocabulary for 'language'

---

README.md

It looks like the docker container configuration for Fedora has changed

Update path for fedora development endpoint

---

app/uploaders/csv_manifest_validator.rb
spec/fixtures/csv_import/csv_files_with_problems/invalid_values.csv
spec/uploaders/csv_manifest_uploader_spec.rb
spec/uploaders/csv_manifest_validator_spec.rb

- Refactors CSVManifestValidator to allow use of mapped values
- Warns when the mapped File Name cannot be found on the disk

Warn on missing File Name

---

.rubocop.yml
app/indexers/collection_indexer.rb
app/indexers/work_indexer.rb
spec/indexers/collection_indexer_spec.rb

Connected to [URS-450](https://jira.library.ucla.edu/browse/URS-450)
---
+ modified: `app/indexers/collection_indexer.rb`
+ modified: `app/indexers/work_indexer.rb`
+ modified: `docker.env`
+ modified: `spec/indexers/collection_indexer_spec.rb`
+ rubocop.yml

Index thumbnail URLs for collections

---

.rubocop.yml
app/assets/stylesheets/application.css
app/importers/californica_importer.rb
app/jobs/start_csv_import_job.rb
app/views/csv_imports/index.html.erb
app/views/csv_imports/show.html.erb
db/migrate/20190827235705_add_times_to_csv_imports.rb
db/schema.rb
spec/system/import_from_csv_spec.rb

[CAL-728](https://jira.library.ucla.edu/browse/CAL-728)
modified:   app/assets/stylesheets/application.css
modified:   app/importers/californica_importer.rb
modified:   app/jobs/start_csv_import_job.rb
modified:   app/views/csv_imports/index.html.erb
modified:   app/views/csv_imports/show.html.erb
new file:   db/migrate/20190827235705_add_times_to_csv_imports.rb
modified:   db/schema.rb
modified:   spec/system/import_from_csv_spec.rb

Add Timing Data

---

app/assets/markdown/importer_guide.md
app/importers/californica_mapper.rb

This matches bucketeer usage and is a better description.

Rename 'access_copy' to 'iiif_access_url'

---

Dockerfile

mysql-client -> mariadb-client
chromedriver -> chromium-driver

Update dockerfile for debian package changes

---

.rubocop.yml
app/controllers/application_controller.rb
spec/controllers/branding_info_controller_spec.rb
spec/controllers/csv_imports_controller_spec.rb
spec/controllers/hyrax/works_controller_spec.rb
spec/controllers/importer_documentation_controller_spec.rb
spec/system/create_child_work_spec.rb
spec/system/create_work_spec.rb
spec/system/import_and_show_work_spec.rb
spec/system/search_catalog_spec.rb

https://jira.library.ucla.edu/browse/CAL-808
modified:    app/controllers/application_controller.rb
modified:   .rubocop.yml
modified:   spec/controllers/branding_info_controller_spec.rb
modified:   spec/controllers/csv_imports_controller_spec.rb
modified:   spec/controllers/hyrax/works_controller_spec.rb
modified:   spec/controllers/importer_documentation_controller_spec.rb
modified:   spec/system/create_child_work_spec.rb
modified:   spec/system/create_work_spec.rb
modified:   spec/system/import_and_show_work_spec.rb
modified:   spec/system/search_catalog_spec.rb

CAL-808 require admin account to do anything

---

app/controllers/application_controller.rb

When we required an administrator login to access californica, this rule was also applied to IIIF manifests, which had the effect of breaking older items in Ursus that weren't imported using the external manifest store. This PR allows IIIF manifests for those items to be retrieved.

allow access to IIIF manifest without login

---

app/controllers/application_controller.rb
app/controllers/csv_imports_controller.rb
app/importers/californica_importer.rb

Connected to: [CAL-798](https://jira.library.ucla.edu/browse/CAL-799)
modified:   app/controllers/csv_imports_controller.rb
modified:   app/importers/californica_importer.rb

Fix CSV Import Unknow status on the index page

---

.rubocop.yml
app/controllers/application_controller.rb

Fixes a bug that prevented new users from creating accounts.

fix: allow creation of new accounts

---

.rubocop.yml
app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb
spec/controllers/csv_imports_controller_spec.rb

fix for infinite loop in read-only mode

---

app/assets/markdown/importer_guide.md
app/importers/californica_mapper.rb
app/models/concerns/discoverable.rb
app/models/solr_document.rb
app/views/hyrax/base/_form_permission.html.erb
app/views/hyrax/base/_form_visibility_component.html.erb
config/initializers/hyrax.rb
config/locales/hyrax.en.yml
spec/importers/californica_mapper_spec.rb
spec/jobs/inherit_permissions_job_spec.rb
spec/models/child_work_spec.rb
spec/models/concerns/discoverable_spec.rb
spec/models/file_set_spec.rb
spec/models/solr_document_spec.rb
spec/models/work_spec.rb
spec/system/edit_file_set_spec.rb
spec/system/edit_visibility_spec.rb

Change name of "discovery" visibility to "sinai"

---

app/assets/markdown/importer_guide.md
app/importers/californica_mapper.rb
spec/importers/californica_mapper_spec.rb

- Adjust importer_guide for Genre field
- Add test for alternate heading for Genre field
- Add alternate heading to CALIFORNICA_TERMS_MAP for Genre field

[CAL-818] Fix up import for Genre field

---

app/importers/californica_mapper.rb
app/models/ucla_metadata.rb
spec/importers/californica_mapper_spec.rb

- uncomment code in place for local_rights_statement
- add test for local_rights_statement

[CAL-709] Fixup import of local_rights_statement

---

app/importers/californica_importer.rb
app/importers/californica_mapper.rb
spec/importers/californica_importer_spec.rb
spec/importers/californica_mapper_spec.rb
spec/system/import_and_show_work_spec.rb

Import 'IIIF Manifest URL', don't generate manifests during ingest

---

.travis.yml

Tagged should go to stage
Branches should go to test

Fix Jenkins deploy hostnames

---

app/controllers/catalog_controller.rb
app/forms/hyrax/californica_collections_form.rb
app/forms/hyrax/work_form.rb
app/importers/californica_mapper.rb
app/models/solr_document.rb
app/models/ucla_metadata.rb
app/presenters/hyrax/californica_collection_presenter.rb
app/presenters/hyrax/work_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
spec/forms/hyrax/work_form_spec.rb
spec/importers/californica_mapper_spec.rb
spec/system/edit_collection_spec.rb
spec/system/edit_work_spec.rb
spec/system/import_and_show_work_spec.rb
spec/system/show_collection_spec.rb
spec/views/hyrax/base/_attribute_rows.html.erb_spec.rb

Local rights statement invokes License renderer from hyrax gem.
connected to  [URS-661](https://jira.library.ucla.edu/browse/URS-661)
modified:   app/controllers/catalog_controller.rb
modified:   app/forms/hyrax/californica_collections_form.rb
modified:   app/forms/hyrax/work_form.rb
modified:   app/importers/californica_mapper.rb
modified:   app/models/solr_document.rb
modified:   app/models/ucla_metadata.rb
modified:   app/presenters/hyrax/californica_collection_presenter.rb
modified:   app/presenters/hyrax/work_presenter.rb
modified:   app/views/hyrax/base/_attribute_rows.html.erb
modified:   spec/forms/hyrax/work_form_spec.rb
modified:   spec/importers/californica_mapper_spec.rb
modified:   spec/system/edit_collection_spec.rb
modified:   spec/system/edit_work_spec.rb
modified: …

Comment local rights statement code, due to errors by license renderer.

---

app/controllers/catalog_controller.rb
solr/config/schema.xml

Connected to [URS-578](https://jira.library.ucla.edu/browse/URS-578)
modified:   app/controllers/catalog_controller.rb
modified:   solr/config/schema.xml

Add new sort field type for title text asc Title (A-Z0-9) & desc Title (Z-A9-0)

---

solr/config/solrconfig.xml

* Add add_hash_id update chain
* Add /update requesthandler to call the add_hash_id update chain

[URS-545] Add hash_id to solrconfig.xml in support of Ursus sitemaps

---

app/importers/californica_mapper.rb

[CAL-878](https://jira.library.ucla.edu/browse/CAL-878)
Remove un-used definition
Acceptance criteria

removed empty definition

---

lib/tasks/delete.rake

rake task to destroy a work and any children

---

app/jobs/reindex_everything_from_solr_job.rb
lib/tasks/reindex.rake

- move logic into asynchronous job
- capture and log exceptions for individual items without cancelling job

Update reindex rake task

---

app/controllers/catalog_controller.rb

updates stored_searchable to _tesim
modified:   app/controllers/catalog_controller.rb

Update catalog controller

---

app/models/ucla_metadata.rb

modified:   app/controllers/catalog_controller.rb

Fix-hyperlinks

---

spec/system/import_mss_from_csv_spec.rb

This test keeps timing out:
`spec/system/import_mss_from_csv_spec.rb`
--
modified:   spec/system/import_mss_from_csv_spec.rb

Comment out flaky test import_mss_from_csv_spec

---

app/views/csv_imports/index.html.erb

Acceptance Criteria
---
modified:   app/views/csv_imports/index.html.erb

CAL-885 Add "created by" data to CSV Import page in Californica

---

app/views/csv_imports/index.html.erb

modified:   app/views/csv_imports/index.html.erb

Fix-csv-imports

---

app/jobs/csv_row_import_job.rb
app/jobs/delete_all_child_works_job.rb
app/lib/californica/deleter.rb
lib/tasks/delete.rake

- Add job to delete all ChildWorks
- Add error handling for Faraday::ConnectionFailed to Californica::Deleter

Updates to ChildWork deletion

---

app/indexers/work_indexer.rb
spec/indexers/work_indexer_spec.rb

blacklight_range_limit can't handle them

don't index negative (BCE) years

---

app/uploaders/csv_manifest_validator.rb
config/authorities/languages.yml

Connected to [APPS-1534](https://jira.library.ucla.edu/browse/APPS-1534) & [APPS-2313](https://jira.library.ucla.edu/browse/APPS-2313)

feat: add new language codes & fix validator for licenses

---

.github/workflows/on-tagged-release.yml

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
The curl action isn't passed through a shell for interpretation
JIRA: APPS-2330 / Automatic Jenkins Build Fail

Use GitHub Context variables

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
app/models/ucla_metadata.rb

index local_identifier as a whole string use symbol

feat: APPS-1692

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
app/models/ucla_metadata.rb

Reverts UCLALibrary/californica#940
Connected to https://jira.library.ucla.edu/browse/APPS-2359

Revert "feat: APPS-1692"

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
app/models/ucla_metadata.rb

Reverts UCLALibrary/californica#942
Ready to add local_identifier_ssim to stage and prod

Revert "Revert "feat: APPS-1692""

---

config/authorities/languages.yml

Connected to [APPS-2442](https://uclalibrary.atlassian.net/jira/software/c/projects/APPS/boards/12?selectedIssue=APPS-2442)
[APPS-2442]: https://uclalibrary.atlassian.net/browse/APPS-2442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: APPS-2442   Ursus: update languages.yml with new MEAP languages

---

app/lib/californica/deleter.rb

https://uclalibrary.atlassian.net/browse/APPS-2612

in Californica::Deleter, recover from RSolr http errors

---

app/uploaders/csv_manifest_validator.rb

https://uclalibrary.atlassian.net/browse/NOP-50
I've just removed the warning, everything else already worked.

fix: NOP-50 Remove upload warning for "public domain" metadata value

---

app/assets/markdown/importer_guide.md

https://uclalibrary.atlassian.net/browse/NOP-85

fiX: NOP-85 Update Californica Documentation 

---

app/indexers/collection_indexer.rb
app/indexers/work_indexer.rb
app/jobs/reindex_everything_from_solr_job.rb
lib/tasks/reindex.rake

should make the reindexing more robust?

NOP-88: Updates to reindex job
